version: "3"
services:
  backend:
    container_name: lemonaid_backend
    image: "lemonaid_backend:0.1"
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8888:8080"
    networks:
      - lemonaid
    environment:
      - TZ=Asia/Seoul
  nginx:
    restart: always
    container_name: "lemonaid_frontend"
    image: "lemonaid_frontend:0.1"
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - lemonaid
    environment:
      - TZ=Asia/Seoul

networks:
  lemonaid: