version: "3"
services:
  db:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - .data:/var/lib/mysql
    cap_add:
      - SYS_NICE
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
